import "./globals.css";
import { Inter } from "next/font/google";
import CSS from "./lib/css/component";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CSS />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
